---
- name: Install required packages
  package:
    name: "{{ capra_lvm_filesystem_packages }}"
    state: present
  tags: [capra-lvm-filesystem-prerequisites]

- name: Configure default mountpoint directory
  file:
    path: "{{ capra_lvm_filesystem_parent_path }}"
    state: directory
    owner: "{{ capra_lvm_filesystem_owner }}"
    group: "{{ capra_lvm_filesystem_group }}"
    mode: 0755
    seuser: unconfined_u
    serole: object_r
    setype: default_t
    selevel: s0
  tags: [capra-lvm-filesystem-prerequisites]

- import_tasks: volume-absent.yaml
  tags: [capra-lvm-filesystem-remove]

- import_tasks: volume-present.yaml
  tags: [capra-lvm-filesystem-create]