---
- name: Install required packages
  package:
    name: "{{ capra_lvm_filesystem_packages }}"
    state: present

- name: Configure default mountpoint directory
  file:
    path: "{{ capra_lvm_filesystem_parent_path }}"
    state: directory
    owner: "{{ capra_lvm_filesystem_owner }}"
    group: "{{ capra_lvm_filesystem_group }}"
    mode: 0755
    seuser: unconfined_u
    serole: object_r
    setype: default_t
    selevel: s0

- name: Create logical volume
  lvol:
    vg: "{{ item.vg | default(capra_lvm_filesystem_vg) }}"
    lv: "{{ item.name | mandatory }}"
    size: "{{ item.size | human_to_bytes }}B"
    opts: "{{ capra_lvm_filesystem_lvcreate_options }}"
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'

- name: Create filesystem
  filesystem:
    fstype: "{{ item.fstype | default(capra_lvm_filesystem_fstype) }}"
    dev: "/dev/{{ item.vg | default(capra_lvm_filesystem_vg) }}/{{ item.name }}"
    opts: "{{ capra_lvm_filesystem_filesystem_options }}"
    resizefs: true
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'

- name: Mount volume
  mount:
    path: "{{ item.path | default(capra_lvm_filesystem_parent_path + '/' + item.name) }}"
    src: "/dev/{{ item.vg | default(capra_lvm_filesystem_vg) }}/{{ item.name }}"
    fstype: "{{ item.fstype | default(capra_lvm_filesystem_fstype) }}"
    opts: "{{ item.options | default(capra_lvm_filesystem_options) }}"
    state: mounted
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'

- name: Set volume permissions
  file:
    path: "{{ item.path | default(capra_lvm_filesystem_parent_path + '/' + item.name) }}"
    state: directory
    owner: "{{ item.owner | default(capra_lvm_filesystem_owner) }}"
    group: "{{ item.group | default(capra_lvm_filesystem_group) }}"
    mode: "{{ item.mode | default(capra_lvm_filesystem_mode) }}"
    seuser: "{{ item.seuser | default(capra_lvm_filesystem_seuser) }}"
    serole: "{{ item.serole | default(capra_lvm_filesystem_serole) }}"
    setype: "{{ item.setype | default(capra_lvm_filesystem_setype) }}"
    selevel: "{{ item.selevel | default(capra_lvm_filesystem_selevel) }}"
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'
