- name: Unmount volume
  mount:
    path: "{{ r_capra_lvm_filesystem_path }}"
    state: absent
  with_indexed_items: "{{ capra_lvm_filesystem_specs }}"

- name: Remove logical volume
  lvol:
    vg: "{{ item[1].vg | default(capra_lvm_filesystem_vg) }}"
    lv: "{{ item[1].name | mandatory }}"
    state: absent
    force: yes
  with_indexed_items: "{{ capra_lvm_filesystem_specs }}"
