- name: Unmount volume
  mount:
    path: "{{ item.mount | default(capra_lvm_filesystem_mount_parent + '/' + item.name) }}"
    state: absent
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'absent'
