- name: Create logical volume
  lvol:
    vg: "{{ item.vg | default(capra_lvm_filesystem_vg) }}"
    lv: "{{ item.name | mandatory }}"
    size: "{{ item.size | human_to_bytes }}B"
    opts: "{{ capra_lvm_filesystem_lvcreate_options }}"
    state: present
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'

- name: Create filesystem
  filesystem:
    fstype: "{{ item.fstype | default(capra_lvm_filesystem_fstype) }}"
    dev: "/dev/{{ item.vg | default(capra_lvm_filesystem_vg) }}/{{ item.name }}"
    opts: "{{ capra_lvm_filesystem_filesystem_options }}"
    resizefs: true
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'

- name: Look up volume UUIDs
  command: >-
    /sbin/blkid
    -c /dev/null
    -o value
    -s UUID
    {{ '/dev/' ~ r_capra_lvm_filesystem_vg ~ '/' ~ item.name | quote }}
  changed_when: false
  register: r_capra_lvm_filesystem_blkid
  with_list: "{{ capra_lvm_filesystem_specs }}"
  tags: [always]
  check_mode: false
  when: (item.state | default('present')) == 'present'
  vars:
    r_capra_lvm_filesystem_vg: "{{ item.vg | default(capra_lvm_filesystem_vg) }}"

- name: Mount volume
  mount:
    path: "{{ item.1.path | default(capra_lvm_filesystem_parent_path + '/' + item.1.name) }}"
    src: "UUID={{ r_capra_lvm_filesystem_blkid.results[item.0].stdout }}"
    fstype: "{{ item.1.fstype | default(capra_lvm_filesystem_fstype) }}"
    opts: "{{ item.1.options | default(capra_lvm_filesystem_options) }}"
    state: mounted
  with_indexed_items: "{{ capra_lvm_filesystem_specs }}"
  when: (item.1.state | default('present')) == 'present'

- name: Set volume permissions
  file:
    path: "{{ item.path | default(capra_lvm_filesystem_parent_path + '/' + item.name) }}"
    state: directory
    owner: "{{ item.owner | default(capra_lvm_filesystem_owner) }}"
    group: "{{ item.group | default(capra_lvm_filesystem_group) }}"
    mode: "{{ item.mode | default(capra_lvm_filesystem_mode) }}"
    seuser: "{{ item.seuser | default(capra_lvm_filesystem_seuser) }}"
    serole: "{{ item.serole | default(capra_lvm_filesystem_serole) }}"
    setype: "{{ item.setype | default(capra_lvm_filesystem_setype) }}"
    selevel: "{{ item.selevel | default(capra_lvm_filesystem_selevel) }}"
  with_list: "{{ capra_lvm_filesystem_specs }}"
  when: (item.state | default('present')) == 'present'
